/*
 * Copyright 2015 Michael Bausano & Pavel Koch
 * This is a beta version of some random game
 */
package game.menu;

import game.world.Renderer;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Pavel
 */
public class MainMenu extends JPanel {
    
    private final JFrame frame;
    private final static Dimension dimens = new Dimension(800, 600);
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        this.initComponents( );
        
        this.frame = new JFrame("Main Menu");
        this.frame.setSize(dimens);
        this.frame.setMinimumSize(dimens);
        this.frame.setMaximumSize(dimens);
        this.frame.setResizable(false);
        this.frame.setLocationRelativeTo(null);
        this.frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.frame.pack();
        this.frame.add( this );
        this.frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewGame = new javax.swing.JButton();
        Settings = new javax.swing.JButton();
        Load = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        NewGame.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        NewGame.setText("New Game");
        NewGame.setBorder(null);
        NewGame.setBorderPainted(false);
        NewGame.setContentAreaFilled(false);
        NewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewGame.setFocusPainted(false);
        NewGame.setMaximumSize(new java.awt.Dimension(150, 50));
        NewGame.setMinimumSize(new java.awt.Dimension(150, 50));
        NewGame.setPreferredSize(new java.awt.Dimension(150, 50));
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });

        Settings.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        Settings.setText("Settings");
        Settings.setBorder(null);
        Settings.setBorderPainted(false);
        Settings.setContentAreaFilled(false);
        Settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Settings.setFocusPainted(false);
        Settings.setMaximumSize(new java.awt.Dimension(150, 50));
        Settings.setMinimumSize(new java.awt.Dimension(150, 50));
        Settings.setPreferredSize(new java.awt.Dimension(150, 50));
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });

        Load.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        Load.setText("Load");
        Load.setBorder(null);
        Load.setBorderPainted(false);
        Load.setContentAreaFilled(false);
        Load.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Load.setFocusPainted(false);
        Load.setMaximumSize(new java.awt.Dimension(150, 50));
        Load.setMinimumSize(new java.awt.Dimension(150, 50));
        Load.setPreferredSize(new java.awt.Dimension(150, 50));
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFocusPainted(false);
        Exit.setMaximumSize(new java.awt.Dimension(150, 50));
        Exit.setMinimumSize(new java.awt.Dimension(150, 50));
        Exit.setPreferredSize(new java.awt.Dimension(150, 50));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Load, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(610, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Load, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsActionPerformed

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
        this.frame.dispose( );
        Renderer r = new Renderer( );
        r.run( );
    }//GEN-LAST:event_NewGameActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Runtime.getRuntime().exit( 1 );
    }//GEN-LAST:event_ExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Load;
    private javax.swing.JButton NewGame;
    private javax.swing.JButton Settings;
    // End of variables declaration//GEN-END:variables
}
